services:
  database:
    image: postgres:17.4
    restart: always
    container_name: timeflow_DB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: balaguru4580/timeflow:backend
    container_name: timeflow_backend
    restart: always
    depends_on:
      - database
    environment:
      PORT: 5000 # internal port
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}

  frontend:
    image: balaguru4580/timeflow:frontend
    container_name: timeflow_frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: timeflow_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
