services:
  database:
    image: postgres:17.4
    restart: always
    container_name: timeflow_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: timeflow_backend
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: timeflow_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
