services:
  database:
    image: postgres:17.4
    restart: always
    container_name: timeflow_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: timeflow_backend
    depends_on:
      - database
    environment:
      PORT: 5000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    # ports:
    #   - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "/api" # This only seems to work locally, but might be phased out since nginx is handling things now, so no need to know local backend loaction
    container_name: timeflow_frontend
    depends_on:
      - backend
    # ports:
    #   - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: timeflow_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data: