services:
  database:
    image: postgres:17.4
    restart: always
    container_name: timeflow_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9626
      POSTGRES_DB: SkinnerFlowDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: timeflow_backend
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:9626@database:5432/mydatabase
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: timeflow_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
