name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push All Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Run only when build is passing on BuildandPush workflow
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest
    
    steps:
      - name:  Checkout repo
        uses: actions/checkout@v3

      - name:  Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name:  Deploy using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} << 'EOF'
            echo " Navigate to project directory..."
            cd /home/ubuntu/TimeFlow

            echo "Pull latest code"
            git fetch --all
            git reset --hard origin/master

            echo "Pull latest images"
            docker-compose -f docker-compose.prod.yml pull

            echo "Stop old containers (if any)"
            docker-compose -f docker-compose.prod.yml down
            
            echo "Start new containers"
            docker-compose -f docker-compose.prod.yml up -d

            echo "Deploy done"
            docker-compose -f docker-compose.prod.yml ps
          EOF
